# --- HDFS ---
hdfs.uri=hdfs://namenode:8020
hdfs.file.path=/nifi_output/merge.csv

# --- Kafka ---
kafka.bootstrap.servers=kafka:9092
kafka.topic=flights
kafka.partitions=4

# --- Replay Engine ---
replay.acceleration.factor=20000

# --- Flink ---
flink.parallelism=4
flink.watermark.max.out.of.order.ms=600000
flink.watermark.strategy=bounded

# --- Metrics ---
# Frequenza del report di throughput (ms)
metrics.throughput.report.interval.ms=5000
# Frequenza del report di latenza (ms)
metrics.latency.report.interval.ms=5000
# Report out-of-order ogni N eventi
metrics.ooo.report.every.events=1000
