# Variabili HDFS
hdfs.uri=hdfs://namenode:8020
hdfs.file.path=/nifi_output/merge.csv

# Variabili Kafka
kafka.bootstrap.servers=kafka:9092
kafka.topic=flights
kafka.partitions=4
#kafka.replication.factor=1

# Variabili Replay Engine
replay.acceleration.factor=20000

# Variabili Flink
flink.parallelism=4